#
# -*- coding: utf-8; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

git:
  depth: 150

branches:
  only:
    - master

language: bash

before_script:
  - sudo apt-get update -qq

  # Install OE dependencies
  # -----------------------
  - sudo apt-get install -qq gawk
  - sudo apt-get install -qq wget
  - sudo apt-get install -qq git-core
  - sudo apt-get install -qq diffstat
  - sudo apt-get install -qq unzip
  - sudo apt-get install -qq texinfo
  - sudo apt-get install -qq gcc-multilib
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq chrpath
  - sudo apt-get install -qq socat
  - sudo apt-get install -qq libsdl1.2-dev
  - sudo apt-get install -qq xterm

  # Install git
  # -----------
  - sudo apt-get install -qq git

  # Create and initialize the build environment
  # -------------------------------------------
  - rm -rf /tmp/build_env
  - git clone git://git.openembedded.org/openembedded-core /tmp/build_env
  - git clone git://git.openembedded.org/bitbake /tmp/build_env/bitbake
  - git clone $(pwd) /tmp/build_env/$(basename $(pwd))

script:
  - source /tmp/build_env/oe-init-build-env && echo "BBLAYERS +=\"/tmp/build_env/meta-musl\"" >> $(pwd)/conf/bblayers.conf && TCLIBC=musl MACHINE=qemux86 bitbake -k world
  - source /tmp/build_env/oe-init-build-env && echo "BBLAYERS +=\"/tmp/build_env/meta-musl\"" >> $(pwd)/conf/bblayers.conf && TCLIBC=musl MACHINE=qemux86-64 bitbake -k world
  - source /tmp/build_env/oe-init-build-env && echo "BBLAYERS +=\"/tmp/build_env/meta-musl\"" >> $(pwd)/conf/bblayers.conf && TCLIBC=musl MACHINE=qemuarm bitbake -k world
  - source /tmp/build_env/oe-init-build-env && echo "BBLAYERS +=\"/tmp/build_env/meta-musl\"" >> $(pwd)/conf/bblayers.conf && TCLIBC=musl MACHINE=qemuarm64 bitbake -k world
  - source /tmp/build_env/oe-init-build-env && echo "BBLAYERS +=\"/tmp/build_env/meta-musl\"" >> $(pwd)/conf/bblayers.conf && TCLIBC=musl MACHINE=qemuppc bitbake -k world
  - source /tmp/build_env/oe-init-build-env && echo "BBLAYERS +=\"/tmp/build_env/meta-musl\"" >> $(pwd)/conf/bblayers.conf && TCLIBC=musl MACHINE=qemumips bitbake -k world
